server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/talenthub
          jwk-set-uri: http://keycloak:8080/realms/talenthub/protocol/openid-connect/certs

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: public-job
              uri: http://job-service:8081
              predicates:
                - Path=/api/v1/public/jobs/**
            - id: secured-job
              uri: http://job-service:8081
              predicates:
                - Path=/api/v1/jobs/**
              filters:
                - name: RequestRateLimiter
                  args:
                    # Số lượng token được nạp lại vào giỏ trong 1 giây (Tốc độ trung bình)
                    redis-rate-limiter.replenishRate: 10
                    # Sức chứa tối đa của giỏ (Cho phép bùng nổ - Burst trong 1 giây tối đa bao nhiêu)
                    redis-rate-limiter.burstCapacity: 20
                    # Mỗi request tốn bao nhiêu token
                    redis-rate-limiter.requestedTokens: 1
                    # SpEL
            - id: candidate-service
              uri: lb://candidate-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/candidates/**
            - id: application-service
              uri: lb://application-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/applications/**
            #                - name: Header
            #                  args:
            #                    header: X-Client-Type
            #                    regex: Web
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/notifications/**
            - id: cv-parser-service
              uri: lb://cv-parser-service
              predicates:
                - name: Path
                  args:
                    pattern: /api/v1/cv-parse/**
          globalcors:
            cors-configurations:
              [ /** ]:
                allowed-origins:
                  - "http://localhost:3000"
                  - "http://localhost:5173"
                  - "https://talenthub.fpt.edu.vn"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowed-headers: "*"
                allow-credentials: true
                max-age: 3600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      access: unrestricted
