server:
  port: 8085
spring:
  application:
    name: cv-parser-service

  # Kết nối RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: talenthub
    password: talenthub
    listener:
      simple:
        default-requeue-rejected: false
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000
          multiplier: 2.0
          max-attempts: 3
          max-interval: 10000

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info